dist: xenial
language: python
python: 3.7
branches:
  only:
  - master

script: true

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GH_TOKEN"
    local_dir: site
    on:
      branch: master