dist: xenial
language: python
python: 3.7
branches:
  only:
    - main
    - dev
install:
- pip install meth5
script: true

deploy:

  - provider: script
    skip_cleanup: true
    on:
      branch: dev
    script: bash ./deploy_anaconda.sh $CONDA_DEV_TOKEN

