{% set version = "0.3.0" %}
{% set name = "meth5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "

  entry_points:
    - meth5=meth5.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.7
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - numpy>=1.19.2
    - scipy==1.4.1
    - pandas>=1.1.3
    - h5py>=2.10.0
about:
  home: https://github.com/snajder-r/meth5format
  license: MIT
  licence_url: https://opensource.org/licenses/MIT
  summary: HDF5 based file format for storage, retrieval, and analysis of modification predictions from Nanopore

extra:
  author: Rene Snajder
  author_email: r.snajder@dkfz-heidelberg.de
  author_url: https://github.com/snajder-r